# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Documenti',
        ),
    ]
