# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170408_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documenti',
            new_name='Document',
        ),
    ]
