# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170408_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='autore',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='testo',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='titolo',
            new_name='title',
        ),
    ]
